[package]
name = "no_kernel"
version = "0.1.0"
edition = "2021"
authors= [""]



# [[bin]]
# name="no_kernel"
# crate-type = ["staticlib"]


[dependencies]
# bootloader = "*"
# anyhow = { version = "1.0.75", default-features = false,features = []}
bootloader_api = "0.11.4"
