[package]
name = "no_kernel"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[lib]
name = "no_kernel"
crate-type = ["staticlib"]
path="src/kernel.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[build-dependencies]
nasm-rs = "0.2.5"
